apiVersion: v1
kind: Service
metadata:
  name: temp-mon-web
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 32000
  selector:
    app: temp-mon-web
  type: NodePort
