version: '3'
services:
  TempMonSensor:
    image: temp-mon-sensor
    container_name: TempMonSensor
    restart: unless-stopped
    volumes:
      - /sys/bus/w1/devices/28-8940561a64ff/w1_slave:/dev/sensor
    ports:
      - 80:80  
