apiVersion: v1
kind: Service
metadata: 
  name: tempmon-frontend
spec:
  type: ClusterIP
  selector:
    app: temp-mon-web
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-mon-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp-mon-web
  template:
    metadata:
      labels:
        app: temp-mon-web
    spec:
      # nodeSelector:
      #   location: subcloud  # Location of desired node
      containers:
      - name: temp-mon-web-frontend
        image: sifotes/4901capstone-tempmonweb #Public image from DockerHub
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: temp-db
          mountPath: /app/db
        env:
        - name: SENSOR_URL
          value: "http://temp-mon-web-backend"
      volumes:
      - name: temp-db
        emptyDir: {}
        
