apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-mon-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp-mon-db
  template:
    metadata:
      labels:
        app: temp-mon-db
    spec:
       #nodeSelector:
       #  location: subcloud  # Location of desired node
      containers:
      - name: temp-mon-web
        image: sifotes/4901capstone-tempmondb #Public image from DockerHub
        # imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 27017
        env:
        - name: SENSOR_URL
          value: "http://temp-mon-sensor"
      volumes:
      - name: temp-db
        emptyDir: {}
