apiVersion: v1
kind: Service
metadata:
  name: temp-mon-web
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 32100
  selector:
    app: temp-mon-web
  type: NodePort    
---
apiVersion: v1
kind: Service
metadata:
  name: temp-mon-db
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 27017
  selector:
    app: temp-mon-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: temp-mon-sensor
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
  selector:
    app: temp-mon-sensor
  type: ClusterIP
